// internal/extractors/javascript/testdata/vue_internals/CrossFrameworkQuery.vue
<script setup lang="ts">
// Cross-framework idioms inside a Vue SFC (#2910):
//  - @tanstack/vue-query useQuery / useMutation / useInfiniteQuery
//  - framework-agnostic Redux Toolkit configureStore / createSlice
import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/vue-query'
import { configureStore, createSlice } from '@reduxjs/toolkit'

const todos = useQuery({ queryKey: ['todos'], queryFn: fetchTodos })
const addTodo = useMutation({ mutationFn: postTodo })
const pages = useInfiniteQuery({ queryKey: ['feed'], queryFn: fetchPage })

const counterSlice = createSlice({
  name: 'counter',
  initialState: { value: 0 },
  reducers: {
    increment(state) { state.value += 1 },
  },
})

const store = configureStore({ reducer: counterSlice.reducer })

async function fetchTodos() { return [] }
async function postTodo() { return {} }
async function fetchPage() { return [] }
</script>

<template>
  <div>{{ todos.data }}</div>
</template>

// internal/extractors/javascript/testdata/svelte_internals/CrossFrameworkQuery.svelte
<script lang="ts">
  // Cross-framework idioms inside a Svelte component (#2910):
  //  - @tanstack/svelte-query createQuery / createMutation / createInfiniteQuery
  //  - framework-agnostic Redux Toolkit createSlice / configureStore
  import { createQuery, createMutation, createInfiniteQuery } from '@tanstack/svelte-query'
  import { configureStore, createSlice } from '@reduxjs/toolkit'

  const todos = createQuery({ queryKey: ['todos'], queryFn: fetchTodos })
  const addTodo = createMutation({ mutationFn: postTodo })
  const feed = createInfiniteQuery({ queryKey: ['feed'], queryFn: fetchPage })

  const counterSlice = createSlice({
    name: 'counter',
    initialState: { value: 0 },
    reducers: {
      increment(state) { state.value += 1 },
    },
  })

  const store = configureStore({ reducer: counterSlice.reducer })

  async function fetchTodos() { return [] }
  async function postTodo() { return {} }
  async function fetchPage() { return [] }
</script>

<div>{$todos.data}</div>
